### ISSUE TITLE
[STYLE] Kakao Map API 스타일 적용

### ISSUE THREAD

**Issue by DaftenP** [DaftenP/supreme-guide#38]
## 📑 작업 사항 
Kakao Map API 스타일 적용

## To-do
- [x] 유형 별 검색결과 필터링
- [x] 유형 별 마커 이미지 분기 처리
- [ ] 마커 클러스터링
- [ ] 인포윈도우 스타일
- [ ] 관광지 검색 결과 스타일
